const locale_zh = {
  // override default English locale to your custom
  ZoomIn: 'Zoom in',
  ZoomOut: 'Zoom out',
  Hand: 'Move',
  History: 'Operation record',
  Crop: 'Crop',
  Load: 'Replace picture',
  DeleteAll: 'Delete all',
  Delete: 'Delete',
  Undo: 'Undo',
  Redo: 'Anti-undo',
  Reset: 'Reset',
  Flip: 'Mirror',
  Rotate: 'Rotate',
  Draw: 'draw',
  Shape: 'Shape annotation',
  Icon: 'Icon label',
  Text: 'Text annotation',
  Mask: 'Mask',
  Filter: 'Filter',
  Bold: 'Bold',
  Italic: 'Italic',
  Underline: 'Underline',
  Left: 'Left aligned',
  Center: 'Centered',
  Right: 'Align right',
  Color: 'Color',
  'Text size': 'Font size',
  Custom: 'Customize',
  Square: 'square',
  Apply: 'Apply',
  Cancel: 'Cancel',
  'Flip X': 'X axis',
  'Flip Y': 'Y axis',
  Range: 'range',
  Stroke: 'Stroke',
  Fill: 'Fill',
  Circle: 'circle',
  Triangle: 'Triangle',
  Rectangle: 'Rectangle',
  Free: 'Curve',
  Straight: 'Straight',
  Arrow: 'arrow',
  'Arrow-2': 'Arrow2',
  'Arrow-3': 'Arrow3',
  'Star-1': 'Star1',
  'Star-2': 'Star-2',
  Polygon: 'Polygon',
  Location: 'Location',
  Heart: 'Heart-shaped',
  Bubble: 'Bubble',
  'Custom icon': 'Custom icon',
  'Load Mask Image': 'Load mask image',
  Grayscale: 'Grayscale',
  Blur: 'Blurred',
  Sharpen: 'Sharpen',
  Emboss: 'Embossed',
  'Remove White': 'Remove white',
  Distance: 'Distance',
  Brightness: 'Brightness',
  Noise: 'Noise',
  'Color Filter': 'Color filter',
  Sepia: 'brown',
  Sepia2: 'brown2',
  Invert: 'Negative',
  Pixelate: 'Pixelize',
  Threshold: 'Threshold',
  Tint: 'Tint',
  Multiply: 'Multiply',
  Blend: 'Mix color',
  Double: 'Double click',
  Download: 'Preview image',
  Resize: 'Resize width and height',
}

export default locale_zh
