const defaultSetting = {
  title: 'GSTP - Giám sát thu phí',
  showSettings: false,
  tagsView: false,
  fixedHeader: true,
  sidebarLogo: true,
}
export const LIST_DIRECTION_CONFIG = [
  {
    name: 'PT',
    value: 'PT',
  },
  {
    name: 'TT',
    value: 'TT',
  },
]
export const LIST_APP_CONFIG = [
  {
    name: 'ATMS',
    code: 'ATMS', // không đổi
    port: '6868',
    icon: 'icon-atms',
    group: 1,
    checkRole: true,
    id: 1,
  },
  {
    name: 'CCTV',
    code: 'CCTV',
    port: '9094',
    icon: 'icon-cctv',
    group: 1,
    checkRole: true,
    id: 2,
  },
  {
    name: 'VDS',
    code: 'VDS',
    port: '9097',
    icon: 'icon-vds',
    group: 1,
    checkRole: true,
    id: 3,
  },
  {
    name: 'VMS',
    code: 'VMS',
    port: '9095',
    icon: 'icon-vms',
    group: 1,
    checkRole: true,
    id: 4,
  },
  {
    name: 'FMS',
    code: 'FMS',
    port: '9199',
    icon: 'icon-fms',
    group: 1,
    checkRole: true,
    id: 5,
  },
  {
    name: 'Video Wall',
    code: 'WALL',
    port: '9101',
    icon: 'icon-app-menu-wall',
    group: 1,
    checkRole: true,
    id: 9,
  },
  {
    name: 'TCS',
    code: 'TCS',
    port: '9191',
    icon: 'icon-app-menu-tsc',
    group: 1,
    checkRole: true,
    id: 8,
  },
  {
    name: 'OMS',
    code: 'OMS',
    port: '9009',
    icon: 'icon-app-menu-oms',
    group: 1,
    checkRole: true,
    id: 11,
  },
  {
    name: 'Console Admin',
    code: 'CONSOLE_ADMIN',
    port: '9100',
    icon: 'icon-app-menu-console',
    group: 2,
    checkRole: true,
    id: 7,
  },
  {
    name: 'CMS Web',
    code: 'CMS_WEB',
    port: '9096/wp-login.php',
    icon: 'icon-webadmin',
    group: 2,
    checkRole: true,
    id: 15,
  },
  {
    name: 'EXC',
    code: 'EXC',
    port: '9197',
    icon: 'icon-app-menu-exc',
    group: 2,
    checkRole: true,
    id: 10,
  },
  {
    name: 'Asset',
    code: 'ASSET',
    port: '9198',
    icon: 'icon-app-menu-asset',
    group: 2,
    checkRole: true,
    id: 6,
  },
  {
    name: 'Web Public',
    code: 'WEB_PUBLIC',
    port: import.meta.env.VUE_APP_MODE === 'dev' ? '9098' : '',
    icon: 'icon-webpublic',
    group: 3,
    checkRole: false,
    id: null,
  },
  {
    name: 'Core',
    code: 'CORE',
    port: '9206',
    icon: 'app-core',
    group: 2,
    checkRole: false,
    id: 12,
  },
  {
    name: 'iTMON',
    code: 'IT_MON',
    port: '9900',
    icon: 'app-itmon',
    group: 1,
    checkRole: true,
    id: 14,
  },
]

export default defaultSetting
